plugins:
  - jekyll-relative-links
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - home.md
  - LICENSE.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - examples

remote_theme: rundocs/jekyll-rtd-theme
theme: null
syntax_highlighter_style: colorful
toc:
    enabled: true
    h_min: 1
    h_max: 3

exclude:
  - README.md
  - Makefile
  - CMakeLists.txt
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - build
  - src
  - libuv
  - coroutine-built
  - pthreads4w
  - .github
  - valgrind.supp
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
